// deno-fmt-ignore
export const
  APPLICATION                              = (applicationId) => `/applications/${applicationId}`,
  APPLICATION_COMMAND                      = (applicationId, commandId) => `/applications/${applicationId}/commands/${commandId}`,
  APPLICATION_COMMANDS                     = (applicationId) => `/applications/${applicationId}/commands`,
  APPLICATION_ENTITLEMENT                  = (applicationId, entitlementId) => `/applications/${applicationId}/entitlements/${entitlementId}`,
  APPLICATION_ENTITLEMENT_CONSUME          = (applicationId, entitlementId) => `/applications/${applicationId}/entitlements/${entitlementId}/consume`,
  APPLICATION_ENTITLEMENTS                 = (applicationId) => `/applications/${applicationId}/entitlements`,
  APPLICATION_GUILD_COMMAND                = (applicationId, guildId, commandId) => `/applications/${applicationId}/guilds/${guildId}/commands/${commandId}`,
  APPLICATION_GUILD_COMMAND_PERMISSIONS    = (applicationId, guildId, commandId) => `/applications/${applicationId}/guilds/${guildId}/commands/${commandId}/permissions`,
  APPLICATION_GUILD_COMMANDS               = (applicationId, guildId) => `/applications/${applicationId}/guilds/${guildId}/commands`,
  APPLICATION_GUILD_COMMANDS_PERMISSIONS   = (applicationId, guildId) => `/applications/${applicationId}/guilds/${guildId}/commands/permissions`,
  APPLICATION_ME                           = "/applications/@me",
  APPLICATION_ROLE_CONNECTIONS_METADATA    = (applicationId) => `/applications/${applicationId}/role-connections/metadata`,
  CHANNEL                                  = (channelId) => `/channels/${channelId}`,
  CHANNEL_FOLLOWERS                        = (channelId) => `/channels/${channelId}/followers`,
  CHANNEL_INVITES                          = (channelId) => `/channels/${channelId}/invites`,
  CHANNEL_MESSAGE                          = (channelId, messageId) => `/channels/${channelId}/messages/${messageId}`,
  CHANNEL_MESSAGE_CROSSPOST                = (channelId, messageId) => `/channels/${channelId}/messages/${messageId}/crosspost`,
  CHANNEL_MESSAGE_REACTION                 = (channelId, messageId, emojiName) => `/channels/${channelId}/messages/${messageId}/reactions/${emojiName}`,
  CHANNEL_MESSAGE_REACTION_ME              = (channelId, messageId, emojiName) => `/channels/${channelId}/messages/${messageId}/reactions/${emojiName}/@me`,
  CHANNEL_MESSAGE_REACTION_USER            = (channelId, messageId, emojiName, userId) => `/channels/${channelId}/messages/${messageId}/reactions/${emojiName}/${userId}`,
  CHANNEL_MESSAGE_REACTIONS                = (channelId, messageId) => `/channels/${channelId}/messages/${messageId}/reactions`,
  CHANNEL_MESSAGE_THREADS                  = (channelId, messageId) => `/channels/${channelId}/messages/${messageId}/threads`,
  CHANNEL_MESSAGES                         = (channelId) => `/channels/${channelId}/messages`,
  CHANNEL_MESSAGES_BULK_DELETE             = (channelId) => `/channels/${channelId}/messages/bulk-delete`,
  CHANNEL_PERMISSION                       = (channelId, overwriteId) => `/channels/${channelId}/permissions/${overwriteId}`,
  CHANNEL_PIN                              = (channelId, messageId) => `/channels/${channelId}/pins/${messageId}`,
  CHANNEL_PINS                             = (channelId) => `/channels/${channelId}/pins`,
  CHANNEL_RECIPIENT                        = (channelId, userId) => `/channels/${channelId}/recipients/${userId}`,
  CHANNEL_THREAD_MEMBER                    = (channelId, userId) => `/channels/${channelId}/thread-members/${userId}`,
  CHANNEL_THREAD_MEMBER_ME                 = (channelId) => `/channels/${channelId}/thread-members/@me`,
  CHANNEL_THREAD_MEMBERS                   = (channelId) => `/channels/${channelId}/thread-members`,
  CHANNEL_THREADS                          = (channelId) => `/channels/${channelId}/threads`,
  CHANNEL_THREADS_ARCHIVED_PRIVATE         = (channelId) => `/channels/${channelId}/threads/archived/private`,
  CHANNEL_THREADS_ARCHIVED_PUBLIC          = (channelId) => `/channels/${channelId}/threads/archived/public`,
  CHANNEL_TYPING                           = (channelId) => `/channels/${channelId}/typing`,
  CHANNEL_USER_ME_THREADS_ARCHIVED_PRIVATE = (channelId) => `/channels/${channelId}/users/@me/threads/archived/private`,
  CHANNEL_WEBHOOKS                         = (channelId) => `/channels/${channelId}/webhooks`,
  GATEWAY                                  = "/gateway",
  GATEWAY_BOT                              = "/gateway/bot",
  GUILD                                    = (guildId) => `/guilds/${guildId}`,
  GUILD_AUDIT_LOGS                         = (guildId) => `/guilds/${guildId}/audit-logs`,
  GUILD_AUTO_MODERATION_RULE               = (guildId, ruleId) => `/guilds/${guildId}/auto-moderation/rules/${ruleId}`,
  GUILD_AUTO_MODERATION_RULES              = (guildId) => `/guilds/${guildId}/auto-moderation/rules`,
  GUILD_BAN                                = (guildId, userId) => `/guilds/${guildId}/bans/${userId}`,
  GUILD_BANS                               = (guildId) => `/guilds/${guildId}/bans`,
  GUILD_BULK_BAN                           = (guildId) => `/guilds/${guildId}/bulk-ban`,
  GUILD_CHANNELS                           = (guildId) => `/guilds/${guildId}/channels`,
  GUILD_EMOJI                              = (guildId, emojiId) => `/guilds/${guildId}/emojis/${emojiId}`,
  GUILD_EMOJIS                             = (guildId) => `/guilds/${guildId}/emojis`,
  GUILD_INTEGRATION                        = (guildId, integrationId) => `/guilds/${guildId}/integrations/${integrationId}`,
  GUILD_INTEGRATIONS                       = (guildId) => `/guilds/${guildId}/integrations`,
  GUILD_INVITES                            = (guildId) => `/guilds/${guildId}/invites`,
  GUILD_MEMBER                             = (guildId, userId) => `/guilds/${guildId}/members/${userId}`,
  GUILD_MEMBER_ME                          = (guildId) => `/guilds/${guildId}/members/@me`,
  GUILD_MEMBER_ROLE                        = (guildId, userId, roleId) => `/guilds/${guildId}/members/${userId}/roles/${roleId}`,
  GUILD_MEMBERS                            = (guildId) => `/guilds/${guildId}/members`,
  GUILD_MEMBERS_SEARCH                     = (guildId) => `/guilds/${guildId}/members/search`,
  GUILD_MFA                                = (guildId) => `/guilds/${guildId}/mfa`,
  GUILD_NEW_MEMBER_WELCOME                 = (guildId) => `/guilds/${guildId}/new-member-welcome`,
  GUILD_ONBOARDING                         = (guildId) => `/guilds/${guildId}/onboarding`,
  GUILD_PREVIEW                            = (guildId) => `/guilds/${guildId}/preview`,
  GUILD_PRUNE                              = (guildId) => `/guilds/${guildId}/prune`,
  GUILD_REGIONS                            = (guildId) => `/guilds/${guildId}/regions`,
  GUILD_ROLE                               = (guildId, roleId) => `/guilds/${guildId}/roles/${roleId}`,
  GUILD_ROLES                              = (guildId) => `/guilds/${guildId}/roles`,
  GUILD_SCHEDULED_EVENT                    = (guildId, guildScheduledEventId) => `/guilds/${guildId}/scheduled-events/${guildScheduledEventId}`,
  GUILD_SCHEDULED_EVENT_USERS              = (guildId, guildScheduledEventId) => `/guilds/${guildId}/scheduled-events/${guildScheduledEventId}/users`,
  GUILD_SCHEDULED_EVENTS                   = (guildId) => `/guilds/${guildId}/scheduled-events`,
  GUILD_STICKER                            = (guildId, stickerId) => `/guilds/${guildId}/stickers/${stickerId}`,
  GUILD_STICKERS                           = (guildId) => `/guilds/${guildId}/stickers`,
  GUILD_TEMPLATE                           = (guildId, code) => `/guilds/${guildId}/templates/${code}`,
  GUILD_TEMPLATES                          = (guildId) => `/guilds/${guildId}/templates`,
  GUILD_THREADS_ACTIVE                     = (guildId) => `/guilds/${guildId}/threads/active`,
  GUILD_VANITY_URL                         = (guildId) => `/guilds/${guildId}/vanity-url`,
  GUILD_VOICE_STATE                        = (guildId, userId) => `/guilds/${guildId}/voice-states/${userId}`,
  GUILD_VOICE_STATE_ME                     = (guildId) => `/guilds/${guildId}/voice-states/@me`,
  GUILD_WEBHOOKS                           = (guildId) => `/guilds/${guildId}/webhooks`,
  GUILD_WELCOME_SCREEN                     = (guildId) => `/guilds/${guildId}/welcome-screen`,
  GUILD_WIDGET                             = (guildId) => `/guilds/${guildId}/widget`,
  GUILD_WIDGET_JSON                        = (guildId) => `/guilds/${guildId}/widget.json`,
  GUILD_WIDGET_PNG                         = (guildId) => `/guilds/${guildId}/widget.png`,
  GUILDS                                   = "/guilds",
  GUILDS_TEMPLATE                          = (code) => `/guilds/templates/${code}`,
  INTERACTION_TOKEN_CALLBACK               = (interactionId, interactionToken) => `/interactions/${interactionId}/${interactionToken}/callback`,
  INVITE                                   = (code) => `/invites/${code}`,
  OAUTH2_APPLICATION_ME                    = "/oauth2/applications/@me",
  OAUTH2_KEYS                              = "/oauth2/keys",
  OAUTH2_ME                                = "/oauth2/@me",
  STAGE_INSTANCE                           = (channelId) => `/stage-instances/${channelId}`,
  STAGE_INSTANCES                          = "/stage-instances",
  STICKER                                  = (stickerId) => `/stickers/${stickerId}`,
  STICKER_PACKS                            = "/sticker-packs",
  USER                                     = (userId) => `/users/${userId}`,
  USER_ME                                  = "/users/@me",
  USER_ME_APPLICATION_ROLE_CONNECTION      = (applicationId) => `/users/@me/applications/${applicationId}/role-connection`,
  USER_ME_CHANNELS                         = "/users/@me/channels",
  USER_ME_CONNECTIONS                      = "/users/@me/connections",
  USER_ME_GUILD                            = (guildId) => `/users/@me/guilds/${guildId}`,
  USER_ME_GUILD_MEMBER                     = (guildId) => `/users/@me/guilds/${guildId}/member`,
  USER_ME_GUILDS                           = "/users/@me/guilds",
  VOICE_REGIONS                            = "/voice/regions",
  WEBHOOK                                  = (webhookId) => `/webhooks/${webhookId}`,
  WEBHOOK_TOKEN                            = (webhookId, webhookToken) => `/webhooks/${webhookId}/${webhookToken}`,
  WEBHOOK_TOKEN_GITHUB                     = (webhookId, webhookToken) => `/webhooks/${webhookId}/${webhookToken}/github`,
  WEBHOOK_TOKEN_MESSAGE                    = (webhookId, webhookToken, messageId) => `/webhooks/${webhookId}/${webhookToken}/messages/${messageId}`,
  WEBHOOK_TOKEN_MESSAGE_ORIGINAL           = (webhookId, webhookToken) => `/webhooks/${webhookId}/${webhookToken}/messages/@original`,
  WEBHOOK_TOKEN_SLACK                      = (webhookId, webhookToken) => `/webhooks/${webhookId}/${webhookToken}/slack`;
