import type { Snowflake } from "../../types/src/reference.ts";

// deno-fmt-ignore
export const
  APPLICATION_ACHIEVEMENT                  = (applicationId: Snowflake, achievementId: Snowflake) => `/applications/${applicationId}/achievements/${achievementId}`,
  APPLICATION_ACHIEVEMENTS                 = (applicationId: Snowflake) => `/applications/${applicationId}/achievements`,
  APPLICATION_COMMAND                      = (applicationId: Snowflake, commandId: Snowflake) => `/applications/${applicationId}/commands/${commandId}`,
  APPLICATION_COMMANDS                     = (applicationId: Snowflake) => `/applications/${applicationId}/commands`,
  APPLICATION_ENTITLEMENT                  = (applicationId: Snowflake, entitlementId: Snowflake) => `/applications/${applicationId}/entitlements/${entitlementId}`,
  APPLICATION_ENTITLEMENT_CONSUME          = (applicationId: Snowflake, entitlementId: Snowflake) => `/applications/${applicationId}/entitlements/${entitlementId}/consume`,
  APPLICATION_ENTITLEMENTS                 = (applicationId: Snowflake) => `/applications/${applicationId}/entitlements`,
  APPLICATION_GUILD_COMMAND                = (applicationId: Snowflake, guildId: Snowflake, commandId: Snowflake) => `/applications/${applicationId}/guilds/${guildId}/commands/${commandId}`,
  APPLICATION_GUILD_COMMAND_PERMISSIONS    = (applicationId: Snowflake, guildId: Snowflake, commandId: Snowflake) => `/applications/${applicationId}/guilds/${guildId}/commands/${commandId}/permissions`,
  APPLICATION_GUILD_COMMANDS               = (applicationId: Snowflake, guildId: Snowflake) => `/applications/${applicationId}/guilds/${guildId}/commands`,
  APPLICATION_GUILD_COMMANDS_PERMISSIONS   = (applicationId: Snowflake, guildId: Snowflake) => `/applications/${applicationId}/guilds/${guildId}/commands/permissions`,
  APPLICATION_SKUS                         = (applicationId: Snowflake) => `/applications/${applicationId}/skus`,
  CHANNEL                                  = (channelId: Snowflake) => `/channels/${channelId}`,
  CHANNEL_FOLLOWERS                        = (channelId: Snowflake) => `/channels/${channelId}/followers`,
  CHANNEL_INVITES                          = (channelId: Snowflake) => `/channels/${channelId}/invites`,
  CHANNEL_MESSAGE                          = (channelId: Snowflake, messageId: Snowflake) => `/channels/${channelId}/messages/${messageId}`,
  CHANNEL_MESSAGE_CROSSPOST                = (channelId: Snowflake, messageId: Snowflake) => `/channels/${channelId}/messages/${messageId}/crosspost`,
  CHANNEL_MESSAGE_REACTION                 = (channelId: Snowflake, messageId: Snowflake, emoji: string) => `/channels/${channelId}/messages/${messageId}/reactions/${emoji}`,
  CHANNEL_MESSAGE_REACTION_ME              = (channelId: Snowflake, messageId: Snowflake, emoji: string) => `/channels/${channelId}/messages/${messageId}/reactions/${emoji}/@me`,
  CHANNEL_MESSAGE_REACTION_USER            = (channelId: Snowflake, messageId: Snowflake, emoji: string, userId: Snowflake) => `/channels/${channelId}/messages/${messageId}/reactions/${emoji}/${userId}`,
  CHANNEL_MESSAGE_REACTIONS                = (channelId: Snowflake, messageId: Snowflake) => `/channels/${channelId}/messages/${messageId}/reactions`,
  CHANNEL_MESSAGE_THREADS                  = (channelId: Snowflake, messageId: Snowflake) => `/channels/${channelId}/messages/${messageId}/threads`,
  CHANNEL_MESSAGES                         = (channelId: Snowflake) => `/channels/${channelId}/messages`,
  CHANNEL_MESSAGES_BULK_DELETE             = (channelId: Snowflake) => `/channels/${channelId}/messages/bulk-delete`,
  CHANNEL_PERMISSION                       = (channelId: Snowflake, overwriteId: Snowflake) => `/channels/${channelId}/permissions/${overwriteId}`,
  CHANNEL_PIN                              = (channelId: Snowflake, messageId: Snowflake) => `/channels/${channelId}/pins/${messageId}`,
  CHANNEL_PINS                             = (channelId: Snowflake) => `/channels/${channelId}/pins`,
  CHANNEL_RECIPIENT                        = (channelId: Snowflake, userId: Snowflake) => `/channels/${channelId}/recipients/${userId}`,
  CHANNEL_THREAD_MEMBER                    = (channelId: Snowflake, userId: Snowflake) => `/channels/${channelId}/thread-members/${userId}`,
  CHANNEL_THREAD_MEMBER_ME                 = (channelId: Snowflake) => `/channels/${channelId}/thread-members/@me`,
  CHANNEL_THREAD_MEMBERS                   = (channelId: Snowflake) => `/channels/${channelId}/thread-members`,
  CHANNEL_THREADS                          = (channelId: Snowflake) => `/channels/${channelId}/threads`,
  CHANNEL_THREADS_ARCHIVED_PRIVATE         = (channelId: Snowflake) => `/channels/${channelId}/threads/archived/private`,
  CHANNEL_THREADS_ARCHIVED_PUBLIC          = (channelId: Snowflake) => `/channels/${channelId}/threads/archived/public`,
  CHANNEL_TYPING                           = (channelId: Snowflake) => `/channels/${channelId}/typing`,
  CHANNEL_USER_ME_THREADS_ARCHIVED_PRIVATE = (channelId: Snowflake) => `/channels/${channelId}/users/@me/threads/archived/private`,
  CHANNEL_WEBHOOKS                         = (channelId: Snowflake) => `/channels/${channelId}/webhooks`,
  GATEWAY                                  = "/gateway",
  GATEWAY_BOT                              = "/gateway/bot",
  GUILD                                    = (guildId: Snowflake) => `/guilds/${guildId}`,
  GUILD_AUDIT_LOGS                         = (guildId: Snowflake) => `/guilds/${guildId}/audit-logs`,
  GUILD_BAN                                = (guildId: Snowflake, userId: Snowflake) => `/guilds/${guildId}/bans/${userId}`,
  GUILD_BANS                               = (guildId: Snowflake) => `/guilds/${guildId}/bans`,
  GUILD_CHANNELS                           = (guildId: Snowflake) => `/guilds/${guildId}/channels`,
  GUILD_EMOJI                              = (guildId: Snowflake, emojiId: Snowflake) => `/guilds/${guildId}/emojis/${emojiId}`,
  GUILD_EMOJIS                             = (guildId: Snowflake) => `/guilds/${guildId}/emojis`,
  GUILD_INTEGRATION                        = (guildId: Snowflake, integrationId: Snowflake) => `/guilds/${guildId}/integrations/${integrationId}`,
  GUILD_INTEGRATIONS                       = (guildId: Snowflake) => `/guilds/${guildId}/integrations`,
  GUILD_INVITES                            = (guildId: Snowflake) => `/guilds/${guildId}/invites`,
  GUILD_MEMBER                             = (guildId: Snowflake, userId: Snowflake) => `/guilds/${guildId}/members/${userId}`,
  GUILD_MEMBER_ME                          = (guildId: Snowflake) => `/guilds/${guildId}/members/@me`,
  GUILD_MEMBER_ME_NICK                     = (guildId: Snowflake) => `/guilds/${guildId}/members/@me/nick`,
  GUILD_MEMBER_ROLE                        = (guildId: Snowflake, userId: Snowflake, roleId: Snowflake) => `/guilds/${guildId}/members/${userId}/roles/${roleId}`,
  GUILD_MEMBERS                            = (guildId: Snowflake) => `/guilds/${guildId}/members`,
  GUILD_MEMBERS_SEARCH                     = (guildId: Snowflake) => `/guilds/${guildId}/members/search`,
  GUILD_PREVIEW                            = (guildId: Snowflake) => `/guilds/${guildId}/preview`,
  GUILD_PRUNE                              = (guildId: Snowflake) => `/guilds/${guildId}/prune`,
  GUILD_REGIONS                            = (guildId: Snowflake) => `/guilds/${guildId}/regions`,
  GUILD_ROLE                               = (guildId: Snowflake, roleId: Snowflake) => `/guilds/${guildId}/roles/${roleId}`,
  GUILD_ROLES                              = (guildId: Snowflake) => `/guilds/${guildId}/roles`,
  GUILD_SCHEDULED_EVENT                    = (guildId: Snowflake, guildScheduledEventId: Snowflake) => `/guilds/${guildId}/scheduled-events/${guildScheduledEventId}`,
  GUILD_SCHEDULED_EVENT_USERS              = (guildId: Snowflake, guildScheduledEventId: Snowflake) => `/guilds/${guildId}/scheduled-events/${guildScheduledEventId}/users`,
  GUILD_SCHEDULED_EVENTS                   = (guildId: Snowflake) => `/guilds/${guildId}/scheduled-events`,
  GUILD_STICKER                            = (guildId: Snowflake, stickerId: Snowflake) => `/guilds/${guildId}/stickers/${stickerId}`,
  GUILD_STICKERS                           = (guildId: Snowflake) => `/guilds/${guildId}/stickers`,
  GUILD_TEMPLATE                           = (guildId: Snowflake, templateCode: string) => `/guilds/${guildId}/templates/${templateCode}`,
  GUILD_TEMPLATES                          = (guildId: Snowflake) => `/guilds/${guildId}/templates`,
  GUILD_THREADS_ACTIVE                     = (guildId: Snowflake) => `/guilds/${guildId}/threads/active`,
  GUILD_VANITY_URL                         = (guildId: Snowflake) => `/guilds/${guildId}/vanity-url`,
  GUILD_VOICE_STATE                        = (guildId: Snowflake, userId: Snowflake) => `/guilds/${guildId}/voice-states/${userId}`,
  GUILD_VOICE_STATE_ME                     = (guildId: Snowflake) => `/guilds/${guildId}/voice-states/@me`,
  GUILD_WEBHOOKS                           = (guildId: Snowflake) => `/guilds/${guildId}/webhooks`,
  GUILD_WELCOME_SCREEN                     = (guildId: Snowflake) => `/guilds/${guildId}/welcome-screen`,
  GUILD_WIDGET                             = (guildId: Snowflake) => `/guilds/${guildId}/widget`,
  GUILD_WIDGET_JSON                        = (guildId: Snowflake) => `/guilds/${guildId}/widget.json`,
  GUILD_WIDGET_PNG                         = (guildId: Snowflake) => `/guilds/${guildId}/widget.png`,
  GUILDS                                   = "/guilds",
  GUILDS_TEMPLATE                          = (templateCode: string) => `/guilds/templates/${templateCode}`,
  INTERACTION_TOKEN_CALLBACK               = (interactionId: Snowflake, interactionToken: string) => `/interactions/${interactionId}/${interactionToken}/callback`,
  INVITE                                   = (inviteCode: string) => `/invites/${inviteCode}`,
  LOBBY                                   = (lobbyId: Snowflake) => `/lobbies/${lobbyId}`,
  LOBBY_MEMBER                            = (lobbyId: Snowflake, userId: Snowflake) => `/lobbies/${lobbyId}/members/${userId}`,
  LOBBY_SEND                              = (lobbyId: Snowflake) => `/lobbies/${lobbyId}/send`,
  LOBBIES                                  = "/lobbies",
  LOBBIES_SEARCH                           = "/lobbies/search",
  OAUTH2_APPLICATION_ME                    = "/oauth2/applications/@me",
  OAUTH2_ME                                = "/oauth2/@me",
  STAGE_INSTANCE                           = (channelId: Snowflake) => `/stage-instances/${channelId}`,
  STAGE_INSTANCES                          = "/stage-instances",
  STICKER                                  = (stickerId: Snowflake) => `/stickers/${stickerId}`,
  STICKER_PACKS                            = "/sticker-packs",
  STORE_SKU_DISCOUNT                       = (skuId: Snowflake, userId: Snowflake) => `/store/skus/${skuId}/discounts/${userId}`,
  USER                                     = (userId: Snowflake) => `/users/${userId}`,
  USER_APPLICATION_ACHIEVEMENT             = (userId: Snowflake, applicationId: Snowflake, achievementId: Snowflake) => `/users/${userId}/applications/${applicationId}//achievements/${achievementId}`,
  USER_ME                                  = "/users/@me",
  USER_ME_CHANNELS                         = "/users/@me/channels",
  USER_ME_CONNECTIONS                      = "/users/@me/connections",
  USER_ME_GUILD                            = (guildId: Snowflake) => `/users/@me/guilds/${guildId}`,
  USER_ME_GUILD_MEMBER                     = (guildId: Snowflake) => `/users/@me/guilds/${guildId}/member`,
  USER_ME_GUILDS                           = "/users/@me/guilds",
  VOICE_REGIONS                            = "/voice/regions",
  WEBHOOK                                  = (webhookId: Snowflake) => `/webhooks/${webhookId}`,
  WEBHOOK_TOKEN                            = (applicationId: Snowflake, interactionToken: string) => `/webhooks/${applicationId}/${interactionToken}`,
  WEBHOOK_TOKEN_GITHUB                     = (webhookId: Snowflake, webhookToken: string) => `/webhooks/${webhookId}/${webhookToken}/github`,
  WEBHOOK_TOKEN_MESSAGE                    = (applicationId: Snowflake, interactionToken: string, messageId: Snowflake) => `/webhooks/${applicationId}/${interactionToken}/messages/${messageId}`,
  WEBHOOK_TOKEN_MESSAGE_ORIGINAL           = (applicationId: Snowflake, interactionToken: string) => `/webhooks/${applicationId}/${interactionToken}/messages/@original`,
  WEBHOOK_TOKEN_SLACK                      = (webhookId: Snowflake, webhookToken: string) => `/webhooks/${webhookId}/${webhookToken}/slack`;
